name: Test Pipeline
run-name: Triggered by ${{ github.event_name }} on env ${{ github.event.inputs.environment || 'QA' }}

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select Env to run Test'
        required: true
        default: 'QA'
        type: choice
        options:
        - DEV
        - SANDBOX
        - QA
        - UAT
        - STAGE
        - PROD

  pull_request:
    branches:
    - main

env:
  USERNAME: ${{ secrets.USERNAME }}
  PASSWORD: ${{ secrets.PASSWORD }}

jobs:
  Test:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || 'QA' }}

    steps:
    - name: Clonar el Repo
      uses: actions/checkout@v4

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Test run JS
      run: |
        npm test
